version: '3'
services:
  mysql:
    build:
      context: ../../
      dockerfile: M01-SISTEMAS/docker/Dockerfile
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Sabores1234
